/**
 * End-to-end through a generator that adopts the capability via the public API.
 * INV-2 (byte identity under recording, both paths), INV-9 (optional capability),
 * INV-11, INV-12 (deterministic across runs), INV-15 (scope honesty in a real flow),
 * INV-23 (values never leak), INV-30 (non-RWA config), INV-32 (ZIP path untouched).
 * Category: Request/Response + Scope Boundary + Portability.
 */
import { describe, expect, it } from 'vitest';

import { generateZip } from '../../src/generator';
import { filterProvenanceByPath, hasProvenance } from '../../src/provenance/provenance-result';
import type { ProvenanceResult } from '../../src/provenance/types';
import { extractFilesFromZip } from '../utils/zip-inspector';
import {
  createSyntheticConfig,
  deepFreeze,
  expectSameBytes,
  SYNTHETIC_FILES,
  SyntheticGenerator,
} from './fixtures';
import type { SyntheticConfig } from './fixtures';

function requireProvenance(result: { provenance?: ProvenanceResult }): ProvenanceResult {
  if (result.provenance === undefined) throw new Error('expected provenance on the result');
  return result.provenance;
}

const configVariants: Array<[string, () => SyntheticConfig]> = [
  ['default', createSyntheticConfig],
  [
    'shared ownership, no limit module, optional set',
    () => {
      const c = createSyntheticConfig();
      c.ownership = { type: 'shared', holders: ['H1', 'H2'] };
      c.modules = [{ moduleId: 'plain' }];
      c.settings.optional = 'present';
      return c;
    },
  ],
  ['empty members', () => ({ ...createSyntheticConfig(), members: [] })],
  ['deep-frozen', () => deepFreeze(createSyntheticConfig())],
];

describe('INV-2 — recording never changes generated bytes or configHash', () => {
  describe.each(configVariants)('config: %s', (_label, makeConfig) => {
    it.each([
      ['generate', false],
      ['generate (variant path)', true],
    ])(
      '%s: files byte-identical and configHash equal across true / false / absent',
      (_path, variant) => {
        const generator = new SyntheticGenerator();
        const on = generator.generate(makeConfig(), { recordProvenance: true, variant });
        const off = generator.generate(makeConfig(), { recordProvenance: false, variant });
        const absent = generator.generate(makeConfig(), { variant });

        expect(expectSameBytes(on.files, off.files)).toEqual([]);
        expect(expectSameBytes(on.files, absent.files)).toEqual([]);
        expect(on.metadata.configHash).toBe(off.metadata.configHash);
        expect(on.metadata.configHash).toBe(absent.metadata.configHash);
        expect(on.metadata.fileCount).toBe(off.metadata.fileCount);

        // the only permitted difference is the presence of `provenance`
        expect('provenance' in on).toBe(true);
        expect('provenance' in off).toBe(false);
        expect('provenance' in absent).toBe(false);
        const { provenance: _p, ...onRest } = on;
        expect(onRest).toEqual(off);
      }
    );
  });

  it('the same config object run recorded then un-recorded is untouched (no mutation side channel)', () => {
    const config = createSyntheticConfig();
    const before = JSON.stringify(config);
    new SyntheticGenerator().generate(config, { recordProvenance: true });
    expect(JSON.stringify(config)).toBe(before);
  });

  it('the synthetic templates exercised every read shape (guards the fixture itself)', () => {
    const provenance = requireProvenance(
      new SyntheticGenerator().generate(createSyntheticConfig(), { recordProvenance: true })
    );
    const all = new Set(
      Object.values(provenance.files).flatMap((f) => f.entries.flatMap((e) => e.paths))
    );
    for (const expected of [
      'settings.name',
      'settings.emptyString',
      'settings.flagOff',
      'settings.zero',
      'settings.nothing',
      'settings.explicitUndefined',
      'settings.optional',
      'settings.nested.deep.leaf',
      'createdAt',
      'bytes',
      'lookup',
      'tags',
      'compute',
      'instance',
      'members',
      'members[0]',
      'members[1].weight',
      'emptyList',
      'ownership.type',
      'ownership.ownerAddress',
      'modules[0].config.maxBalance',
      'modules[0].config', // unrepresentable keys fall back to the parent
      'modules[0].config.名前',
    ]) {
      expect(all.has(expected), `missing ${expected}`).toBe(true);
    }
    expect([...all].some((p) => p.includes('weird'))).toBe(false);
  });
});

describe('INV-9 — capability is optional and presence-detected', () => {
  it('a supporting generator with the flag false or absent returns no provenance key', () => {
    const generator = new SyntheticGenerator();
    const off = generator.generate(createSyntheticConfig(), { recordProvenance: false });
    const absent = generator.generate(createSyntheticConfig());
    expect('provenance' in off).toBe(false);
    expect('provenance' in absent).toBe(false);
    expect(hasProvenance(off)).toBe(false);
    expect(hasProvenance(absent)).toBe(false);
  });

  it('a supporting generator with the flag true returns provenance that hasProvenance narrows', () => {
    const on = new SyntheticGenerator().generate(createSyntheticConfig(), {
      recordProvenance: true,
    });
    expect(hasProvenance(on)).toBe(true);
    if (hasProvenance(on)) expect(Object.keys(on.provenance.files).length).toBeGreaterThan(0);
  });
});

describe('INV-12 — deterministic across runs and instances', () => {
  it('two runs on deep-equal configs yield deep-equal provenance', () => {
    const a = requireProvenance(
      new SyntheticGenerator().generate(createSyntheticConfig(), { recordProvenance: true })
    );
    const b = requireProvenance(
      new SyntheticGenerator().generate(createSyntheticConfig(), { recordProvenance: true })
    );
    expect(a).toEqual(b);
  });

  it('interleaved generators (plain and variant racing) do not cross-contaminate', () => {
    const g1 = new SyntheticGenerator();
    const g2 = new SyntheticGenerator();
    const solo = requireProvenance(
      g1.generate(createSyntheticConfig(), { recordProvenance: true })
    );
    const soloVariant = requireProvenance(
      g2.generate(createSyntheticConfig(), { recordProvenance: true, variant: true })
    );
    const again = requireProvenance(
      g1.generate(createSyntheticConfig(), { recordProvenance: true })
    );
    const againVariant = requireProvenance(
      g2.generate(createSyntheticConfig(), { recordProvenance: true, variant: true })
    );
    expect(again).toEqual(solo);
    expect(againVariant).toEqual(soloVariant);
    expect(againVariant.files[SYNTHETIC_FILES.readme]).not.toEqual(
      solo.files[SYNTHETIC_FILES.readme]
    );
  });
});

describe('INV-15 — scope honesty in a real generate flow', () => {
  it('locked controls read by validate() / hashing appear in no entry; every file lists only its own reads', () => {
    const generator = new SyntheticGenerator();
    const provenance = requireProvenance(
      generator.generate(createSyntheticConfig(), { recordProvenance: true })
    );
    expect(generator.rawReadsPerformed).toBe(1);
    const dump = JSON.stringify(provenance);
    expect(dump).not.toContain('locked');
    // ownership.txt read only the ownership branch
    expect(provenance.files[SYNTHETIC_FILES.ownership]?.entries).toEqual([
      { kind: 'file', paths: ['ownership.ownerAddress', 'ownership.type'] },
    ]);
    // members.txt never read settings
    const memberPaths = provenance.files[SYNTHETIC_FILES.members]?.entries[0]?.paths ?? [];
    expect(memberPaths.some((p) => p.startsWith('settings'))).toBe(false);
  });

  it('observe → createdBy: NOTE.txt has a created entry with the decision paths, disjoint from its file entry', () => {
    const provenance = requireProvenance(
      new SyntheticGenerator().generate(createSyntheticConfig(), { recordProvenance: true })
    );
    const entries = provenance.files[SYNTHETIC_FILES.optionalNote]?.entries;
    expect(entries).toEqual([
      { kind: 'file', paths: ['settings.name'] },
      { kind: 'created', paths: ['modules', 'modules[0].moduleId'] },
    ]);
  });

  it('addRange in main.txt attaches a range entry and folds its paths into the file entry', () => {
    const provenance = requireProvenance(
      new SyntheticGenerator().generate(createSyntheticConfig(), { recordProvenance: true })
    );
    const entries = provenance.files[SYNTHETIC_FILES.main]?.entries ?? [];
    const range = entries.find((e) => e.kind === 'range');
    expect(range).toEqual({
      kind: 'range',
      range: { start: 1, end: 2 },
      paths: ['settings.name', 'settings.symbol'],
    });
    expect(entries[0]?.paths).toContain('settings.symbol');
  });

  it('a file emitted outside any scope is absent from provenance (INV-11); recorded files ⊂ emitted files', () => {
    const result = new SyntheticGenerator().generate(createSyntheticConfig(), {
      recordProvenance: true,
    });
    const provenance = requireProvenance(result);
    expect(result.files['UNRECORDED.txt']).toBe('not recorded');
    expect(provenance.files['UNRECORDED.txt']).toBeUndefined();
    for (const key of Object.keys(provenance.files)) expect(result.files[key]).toBeDefined();
  });

  it('spec AS-2 via filter: querying members[1].address lights members.txt and config.json, not ownership.txt', () => {
    const provenance = requireProvenance(
      new SyntheticGenerator().generate(createSyntheticConfig(), { recordProvenance: true })
    );
    const hit = Object.keys(filterProvenanceByPath(provenance, 'members[1].address').files);
    expect(hit).toContain(SYNTHETIC_FILES.members);
    expect(hit).toContain(SYNTHETIC_FILES.configJson);
    // main.txt asks Array.isArray(c.members) — a read of `members`, which is an honest parent match
    expect(hit).toContain(SYNTHETIC_FILES.main);
    expect(hit).not.toContain(SYNTHETIC_FILES.ownership);
    expect(hit).not.toContain(SYNTHETIC_FILES.modules);
  });

  it('the variant path re-emits README: its entries are replaced wholesale and its position kept (INV-18 in flow)', () => {
    const plain = requireProvenance(
      new SyntheticGenerator().generate(createSyntheticConfig(), { recordProvenance: true })
    );
    const variant = requireProvenance(
      new SyntheticGenerator().generate(createSyntheticConfig(), {
        recordProvenance: true,
        variant: true,
      })
    );
    expect(Object.keys(plain.files)).toEqual(Object.keys(variant.files));
    expect(variant.files[SYNTHETIC_FILES.readme]?.entries).toEqual([
      {
        kind: 'file',
        paths: ['settings.decimals', 'settings.name', 'settings.symbol'],
      },
    ]);
  });
});

describe('INV-23 — provenance carries paths, never values', () => {
  it('a config whose every leaf is a distinct sentinel produces a result with no sentinel in it', () => {
    const config = createSyntheticConfig();
    let n = 0;
    const stamp = (): string => `SECRET-${(n += 1)}`;
    config.settings.name = stamp();
    config.settings.symbol = stamp();
    config.settings.emptyString = stamp();
    config.settings.nested.deep.leaf = stamp();
    config.members = [
      { id: stamp(), address: stamp(), weight: 1 },
      { id: stamp(), address: stamp(), weight: 2 },
    ];
    config.ownership = { type: 'single', ownerAddress: stamp() };
    config.modules = [{ moduleId: 'limit', config: { maxBalance: stamp(), 'weird.key': stamp() } }];
    config.locked = { a: stamp(), b: stamp() };
    const result = new SyntheticGenerator().generate(config, { recordProvenance: true });
    expect(JSON.stringify(requireProvenance(result))).not.toContain('SECRET-');
    // sanity: the bytes DO contain them, so the assertion above is meaningful
    expect(JSON.stringify(result.files)).toContain('SECRET-1');
  });
});

describe('INV-32 — the ZIP path is untouched by the capability', () => {
  it('generateZip accepts a result carrying provenance and ZipResult gains no provenance member', async () => {
    const result = new SyntheticGenerator().generate(createSyntheticConfig(), {
      recordProvenance: true,
    });
    const zip = await generateZip(result, 'synthetic');
    expect('provenance' in zip).toBe(false);
    expect(zip.metadata).toBe(result.metadata);
    const entries = await extractFilesFromZip(zip.data);
    const paths = entries.map((e) => e.path).sort();
    expect(paths).toEqual(
      Object.keys(result.files)
        .map((k) => `synthetic/${k}`)
        .sort()
    );
  });

  it('a ZIP built from the recorded result equals one built from the un-recorded result, byte for byte', async () => {
    const generator = new SyntheticGenerator();
    const on = await generateZip(
      generator.generate(createSyntheticConfig(), { recordProvenance: true }),
      'z'
    );
    const off = await generateZip(generator.generate(createSyntheticConfig()), 'z');
    const onEntries = await extractFilesFromZip(on.data);
    const offEntries = await extractFilesFromZip(off.data);
    expect(onEntries).toEqual(offEntries);
  });
});
