/**
 * Core types for the codegen engine.
 *
 * These types define the extensibility contract between the engine
 * and any generator implementation. No chain-specific or domain-specific
 * assumptions are made here.
 */

import type { ProvenanceResult } from './provenance/types';

// ---------------------------------------------------------------------------
// File Tree
// ---------------------------------------------------------------------------

/**
 * In-memory representation of a project's directory structure.
 * Keys are relative paths (e.g., "contracts/token/src/contract.rs").
 * Values are UTF-8 text content or binary data.
 */
export type FileTree = Record<string, string | Uint8Array>;

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export interface ValidationError {
  /** Dot-path to the invalid field, e.g., "token.decimals" */
  field: string;
  /** Machine-readable error code (uppercase snake_case), e.g., "INVALID_RANGE" */
  code: string;
  /** Human-readable description */
  message: string;
}

export interface ValidationWarning {
  field: string;
  code: string;
  message: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
}

// ---------------------------------------------------------------------------
// Progress
// ---------------------------------------------------------------------------

/**
 * Canonical pipeline phase strings used by codegen packages.
 * Generators and the core pipeline must use these values so consumers can map consistently.
 */
export const PROGRESS_PHASES = [
  'validating',
  'generating-contracts',
  'generating-scripts',
  'packaging',
  'assembling-zip',
  'complete',
  'error',
] as const;

export type ProgressPhase = (typeof PROGRESS_PHASES)[number];

/**
 * UI-friendly summary phases for progress display.
 * Use toSummaryPhase() to map ProgressPhase to SummaryPhase.
 */
export type SummaryPhase = 'validating' | 'generating' | 'packaging' | 'success' | 'error';

export interface ProgressEvent {
  /** Current pipeline phase (canonical ProgressPhase). */
  phase: ProgressPhase;
  /** Completion percentage (0–100) */
  percentage: number;
  /** Optional detail message */
  message?: string;
}

export type ProgressCallback = (event: ProgressEvent) => void;

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

export interface GenerateOptions {
  onProgress?: ProgressCallback;
  /**
   * Ask the generator to record which config paths each emitted file read.
   * Generators that support provenance return it as `GenerationResult.provenance`;
   * generators that do not simply ignore the flag. Recording never changes
   * generated bytes or `configHash`.
   */
  recordProvenance?: boolean;
  /**
   * Absolute path to a local checkout of the upstream contracts library.
   * When set, generators resolve contract dependencies via local `path = "…"`
   * instead of a pinned git revision. Useful during development against
   * unmerged branches of the contracts repo.
   */
  contractsLibraryPath?: string;
  /**
   * Allow modules whose review state is not yet "stable".
   * When false (the default), generators should reject or warn about
   * modules that are still under review.
   */
  allowUnderReviewModules?: boolean;
}

export interface GenerationMetadata {
  generatorName: string;
  generatorVersion: string;
  generatedAt: string;
  fileCount: number;
  /** Deterministic hash of the config's stable JSON representation */
  configHash: string;
}

export interface GenerationResult {
  files: FileTree;
  metadata: GenerationMetadata;
  /**
   * Present iff `options.recordProvenance` was true and this generator supports
   * provenance. Absent otherwise. Consumers presence-test with `hasProvenance`.
   */
  provenance?: ProvenanceResult;
}

export interface ZipResult {
  data: Blob;
  fileName: string;
  metadata: GenerationMetadata;
}

// ---------------------------------------------------------------------------
// Generator Interface
// ---------------------------------------------------------------------------

/**
 * The interface that all generators must implement.
 *
 * A generator knows how to:
 * 1. Validate a domain-specific configuration
 * 2. Produce an in-memory file tree from that configuration
 *
 * The core engine handles everything else: ZIP assembly, progress
 * orchestration, and pipeline coordination.
 *
 * @typeParam TConfig - The configuration type this generator accepts.
 */
export interface Generator<TConfig = unknown> {
  readonly name: string;
  readonly version: string;

  /** Validate a configuration without generating output. */
  validate(config: TConfig): ValidationResult;

  /** Generate the file tree from a validated configuration. */
  generate(config: TConfig, options?: GenerateOptions): GenerationResult;
}
