/**
 * The invariants that guard everything OUTSIDE the attribution itself: the
 * published API surface (INV-5, INV-32), the error surface (INV-9), what
 * provenance is allowed to carry (INV-28), what the generator is allowed to do
 * while recording (INV-26, INV-29), and the frozen core boundary (INV-31).
 *
 * These are cheap and none of them existed: every one is a regression that
 * would ship silently, because none of them changes a generated byte.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it, vi } from 'vitest';

import * as stellarApi from '../../src/index';
import { createValidConfig } from '../helpers/config';
import { GENERATE_PATHS, generateRecorded, GOLDEN_FIXTURES } from './helpers';

const sourceFile = (relativePath: string): string =>
  readFileSync(fileURLToPath(new URL(`../../src/${relativePath}`, import.meta.url)), 'utf8');

/* ------------------------------------------------------------------ *
 * INV-5 / INV-32 — the package root is unchanged and the change is additive
 * ------------------------------------------------------------------ */
describe('package-root API surface (INV-5, INV-32)', () => {
  /**
   * Pinned deliberately as a literal list rather than a snapshot file: a
   * snapshot can be refreshed with `-u`, which is the forbidden gesture for
   * this whole stage. Removing or renaming any of these is the breaking change
   * INV-5 says SF-3 must not make; adding one is additive and belongs here
   * with a changeset.
   */
  const PUBLISHED_EXPORTS = [
    'COMPLIANCE_CONFIG_BLOCKING_WARNING_IDS',
    'GENERATED_FILE_KINDS',
    'GENERATED_STELLAR_SOURCE_REPO_URL',
    'IDENTITY_SUPPORT_CONTRACTS',
    'SIGN_CLAIM_TOOL',
    'STELLAR_SEP_0057_CONTRACT_TYPES_URL',
    'STELLAR_VALIDATION_CONSTANTS',
    'StellarRwaGenerator',
    'StellarRwaProgressPhase',
    'formatDeployPostGenerationSteps',
    'formatDeployReadinessChecklist',
    'generate',
    'generateIdentitySupportFiles',
    'generateRoleSymbol',
    'generateWithIdentitySupport',
    'generateZip',
    'generateZipWithIdentitySupport',
    'getAvailableModules',
    'getCodegenInfoBlurb',
    'getComplianceConfigWarnings',
    'getContractsLibraryRepositoryUrl',
    'getDemoMintComplianceWarningId',
    'getDeployGuidance',
    'getEcosystemMetadata',
    'getGeneratedFileKind',
    'getModuleById',
    'getUpstreamImportLinks',
    'getUpstreamSourceRevision',
    'hasComplianceConfigBlockingIssues',
    'isComplianceConfigBlockingWarningId',
    'isDemoAutoMintConfigReady',
    'sanitizeDirectoryName',
    'validate',
  ];

  it('exports exactly the pre-migration set', () => {
    expect(Object.keys(stellarApi).sort()).toEqual(PUBLISHED_EXPORTS);
  });

  /**
   * INV-18: the dual-role helpers stay PURE. Callers wrap them in `observe`, so
   * a helper that grew a sink parameter would silently change every external
   * consumer's call. Arity is the observable part of that contract.
   */
  it.each([
    ['getDeployGuidance', stellarApi.getDeployGuidance, 1],
    ['formatDeployPostGenerationSteps', stellarApi.formatDeployPostGenerationSteps, 1],
    ['formatDeployReadinessChecklist', stellarApi.formatDeployReadinessChecklist, 2],
    ['getComplianceConfigWarnings', stellarApi.getComplianceConfigWarnings, 1],
    ['hasComplianceConfigBlockingIssues', stellarApi.hasComplianceConfigBlockingIssues, 1],
    ['isDemoAutoMintConfigReady', stellarApi.isDemoAutoMintConfigReady, 1],
  ])('%s still takes its pre-migration required arguments', (_name, fn, arity) => {
    expect(fn.length).toBe(arity);
  });

  /** INV-2: recording is opt-in, so an existing caller sees no new own property. */
  it.each(GENERATE_PATHS)('$name adds no own property for an unrecorded call', (path) => {
    const result = path.run(createValidConfig({}));

    expect(Object.prototype.hasOwnProperty.call(result, 'provenance')).toBe(false);
  });
});

/* ------------------------------------------------------------------ *
 * INV-9 — the typed error surface is unchanged; no new error class
 * ------------------------------------------------------------------ */
describe('error surface (INV-9)', () => {
  const invalid = () => createValidConfig({ token: { name: '' } });

  it.each(GENERATE_PATHS)(
    '$name rejects an invalid config the same way with recording on',
    (path) => {
      const withoutRecording = (): unknown => path.run(invalid());
      const withRecording = (): unknown => path.run(invalid(), { recordProvenance: true });

      expect(withoutRecording).toThrowError(Error);
      expect(withRecording).toThrowError(Error);

      let unrecordedMessage = '';
      let recordedMessage = '';
      try {
        withoutRecording();
      } catch (error) {
        unrecordedMessage = (error as Error).message;
      }
      try {
        withRecording();
      } catch (error) {
        recordedMessage = (error as Error).message;
      }

      // INV-13: the flag never reaches a branch that changes behaviour — not even
      // the failure branch, whose message is part of the consumer contract.
      expect(recordedMessage).toBe(unrecordedMessage);
      expect(recordedMessage).toMatch(/^Invalid configuration: /);
    }
  );

  it('exports no provenance-specific error class from the package root', () => {
    const errorLikeExports = Object.entries(stellarApi).filter(
      ([name, value]) => typeof value === 'function' && /Error$/.test(name)
    );

    expect(errorLikeExports).toEqual([]);
  });
});

/* ------------------------------------------------------------------ *
 * INV-28 — provenance carries config PATHS, never config VALUES
 *
 * The strongest privacy statement this SF makes, and the one with real
 * consequences: an RWA config holds owner and issuer addresses. A recorder that
 * leaked a value into a path string would hand every consumer of the wizard's
 * impact list a copy of them.
 * ------------------------------------------------------------------ */
describe('provenance carries paths, never values (INV-28)', () => {
  /** Values a fixture sets that must never appear inside a recorded path. */
  const SECRETS = [
    'Acme Real Estate Token',
    'GCEXAMPLEOWNER',
    'GCEXAMPLEMGR',
    'GCEXAMPLEAGNT',
    'GCEXAMPLEISSUER1',
    'Stellar Testnet',
  ];

  it.each(GENERATE_PATHS)('$name leaks no configured value into any recorded path', (path) => {
    const offenders: string[] = [];

    for (const fixture of GOLDEN_FIXTURES) {
      const { provenance } = generateRecorded(path, fixture.config);
      for (const [filePath, file] of Object.entries(provenance.files)) {
        for (const entry of file.entries) {
          for (const configPath of entry.paths) {
            for (const secret of SECRETS) {
              if (configPath.includes(secret)) {
                offenders.push(`${fixture.name}: ${filePath} → ${configPath}`);
              }
            }
          }
        }
      }
    }

    expect(offenders).toEqual([]);
  });

  /**
   * The complementary shape check: every recorded path is made of config-schema
   * segments and indices only. A value that arrived as a path would almost
   * certainly carry a character this rejects (a space, a quote, a slash).
   */
  it.each(GENERATE_PATHS)('$name records only well-formed dotted config paths', (path) => {
    const wellFormed = /^$|^[A-Za-z_$][A-Za-z0-9_$]*(\[\d+\]|\.[A-Za-z_$][A-Za-z0-9_$]*)*$/;
    const offenders: string[] = [];

    for (const fixture of GOLDEN_FIXTURES) {
      const { provenance } = generateRecorded(path, fixture.config);
      for (const file of Object.values(provenance.files)) {
        for (const entry of file.entries) {
          for (const configPath of entry.paths) {
            if (!wellFormed.test(configPath)) offenders.push(`${fixture.name}: ${configPath}`);
          }
        }
      }
    }

    expect(offenders).toEqual([]);
  });
});

/* ------------------------------------------------------------------ *
 * INV-29 / INV-26 — nothing is logged, nothing is read from disk
 * ------------------------------------------------------------------ */
describe('recording is silent and in-memory (INV-26, INV-29)', () => {
  it.each(GENERATE_PATHS)('$name logs nothing while recording', (path) => {
    const spies = (['log', 'info', 'warn', 'error', 'debug', 'trace'] as const).map((method) =>
      vi.spyOn(console, method).mockImplementation(() => undefined)
    );

    try {
      generateRecorded(path, createValidConfig({}));
      for (const spy of spies) expect(spy).not.toHaveBeenCalled();
    } finally {
      for (const spy of spies) spy.mockRestore();
    }
  });

  /**
   * INV-26 bounds the SHAPE of the cost rather than a wall-clock budget: the
   * generator is browser-safe, so a `node:` import reaching a migrated template
   * is a portability regression as much as a performance one. Asserted against
   * the files this SF actually migrated.
   */
  it.each([
    'stellar-rwa-generator.ts',
    'templates/identity-support.ts',
    'templates/readme.ts',
    'templates/cargo/workspace-toml.ts',
    'templates/contracts/detached-scope.ts',
    'templates/contracts/rwa-token.ts',
    'templates/scripts/deploy-sh.ts',
    'templates/scripts/deploy-sh-post-deploy.ts',
    'templates/scripts/bootstrap-demo-mint-sh.ts',
  ])('%s imports no Node built-in and calls no console method', (relativePath) => {
    const source = sourceFile(relativePath);
    const code = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');

    expect(code).not.toMatch(/from\s+['"]node:/);
    expect(code).not.toMatch(/require\(['"](node:|fs|path)['"]\)/);
    expect(code).not.toMatch(/\bconsole\.\w+\(/);
  });

  /** Recording is synchronous: the result is fully formed on return, not a promise. */
  it.each(GENERATE_PATHS)('$name returns a fully-formed result synchronously', (path) => {
    const result = path.run(createValidConfig({}), { recordProvenance: true });

    expect(result).not.toBeInstanceOf(Promise);
    expect(
      Object.keys((result as { provenance: { files: object } }).provenance.files).length
    ).toBeGreaterThan(0);
  });
});

/* ------------------------------------------------------------------ *
 * INV-31 — the frozen core boundary
 * ------------------------------------------------------------------ */
describe('core stays chain-agnostic (INV-31)', () => {
  /**
   * Constitution I: chain-specific logic lives only in the generator package.
   * The provenance capability SF-1/SF-2 published is generic, and SF-3 must not
   * have taught it any Stellar vocabulary to get the migration done.
   */
  it('has no Stellar vocabulary in the core provenance capability', () => {
    const coreSource = [
      'index.ts',
      'line-builder.ts',
      'patch-builder.ts',
      'provenance-collector.ts',
    ]
      .map((name) =>
        readFileSync(
          fileURLToPath(new URL(`../../../codegen-core/src/provenance/${name}`, import.meta.url)),
          'utf8'
        )
      )
      .join('\n');

    for (const word of ['stellar', 'soroban', 'rwa-token', 'Cargo', 'wasm']) {
      expect(coreSource.toLowerCase()).not.toContain(word.toLowerCase());
    }
  });

  /**
   * INV-30: exactly one emitter. `renderDetached` is how a scope-aware template
   * serves a pure-text caller; a second, non-scoped copy of a template would be
   * the shadow path that drifts from the recorded one while every golden stays
   * green.
   */
  it('routes pure-text callers through the single detached-scope emitter', () => {
    const detached = sourceFile('templates/contracts/detached-scope.ts');

    expect(detached).toContain('renderDetached');
    expect(detached.match(/export function renderDetached/g)).toHaveLength(1);
  });
});
