// Auto-generated by scripts/sync-stellar-templates.mjs. Do not edit by hand.

export const GENERATED_STELLAR_SOURCE_REPO_URL =
  'https://github.com/OpenZeppelin/stellar-contracts.git';
export const GENERATED_STELLAR_SOURCE_COMMIT_HASH = '0c0464ba1f0523938a54234fc73451b2ef2c9228';
export const GENERATED_STELLAR_SOURCE_SYNCED_AT = '2026-05-19T10:57:37.892Z';
