// Auto-generated by scripts/sync-stellar-templates.mjs. Do not edit by hand.

export const GENERATED_STELLAR_SOURCE_REPO_URL = 'https://github.com/pasevin/stellar-contracts.git';
export const GENERATED_STELLAR_SOURCE_COMMIT_HASH = '7ceb527018b07336620e105c877efca15790f8ee';
export const GENERATED_STELLAR_SOURCE_SYNCED_AT = '2026-04-14T21:10:58.560Z';
